# Generated by Django 4.1 on 2023-05-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPricePredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_capacity', models.IntegerField(choices=[(1, 'Petrol'), (2, 'Diesel'), (3, 'Hybrid')])),
                ('model_year', models.IntegerField(choices=[(1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2013, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023')])),
                ('mileage', models.FloatField()),
                ('company', models.CharField(choices=[('Adam', 'Adam'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Chery', 'Chery'), ('Chevrolet', 'Chevrolet'), ('DFSK', 'DFSK'), ('Daewoo', 'Daewoo'), ('Daihatsu', 'Daihatsu'), ('FAW', 'FAW'), ('Fiat', 'Fiat'), ('Honda', 'Honda'), ('Hummer', 'Hummer'), ('Hyundai', 'Hyundai'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('KIA', 'KIA'), ('Land', 'Land'), ('Lexus', 'Lexus'), ('MINI', 'MINI'), ('Mazda', 'Mazda'), ('Mercedes', 'Mercedes'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Porsche', 'Porsche'), ('Range', 'Range'), ('SsangYong', 'SsangYong'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Toyota', 'Toyota'), ('United', 'United'), ('Volvo', 'Volvo')], max_length=100)),
                ('variant', models.CharField(max_length=100)),
                ('engine_type', models.CharField(max_length=100, verbose_name=[(1, 'Petrol'), (2, 'Diesel'), (3, 'Hybrid')])),
                ('transmission', models.CharField(max_length=100, verbose_name=[(1, 'Auto'), (2, 'Manual')])),
                ('body_type', models.CharField(max_length=100, verbose_name=[(1, 'Hatchback'), (2, 'Sedan'), (3, 'Jeep'), (4, 'Van&MiniVan'), (5, 'SUV or crossover'), (6, 'Van')])),
            ],
        ),
    ]
