# Generated by Django 4.1 on 2023-05-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmodel', '0002_alter_carpricepredictionmodel_engine_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpricepredictionmodel',
            name='body_type',
            field=models.CharField(choices=[(1, 'Hatchback'), (2, 'Sedan'), (3, 'Jeep'), (4, 'Van&MiniVan'), (5, 'SUV or crossover'), (6, 'Van')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carpricepredictionmodel',
            name='engine_type',
            field=models.CharField(choices=[(1, 'Petrol'), (2, 'Diesel'), (3, 'Hybrid')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carpricepredictionmodel',
            name='transmission',
            field=models.CharField(choices=[(1, 'Auto'), (2, 'Manual')], max_length=100),
        ),
    ]
