# Generated by Django 4.1 on 2023-05-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmodel', '0003_alter_carpricepredictionmodel_body_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpricepredictionmodel',
            name='body_type',
            field=models.IntegerField(choices=[(1, 'Hatchback'), (2, 'Sedan'), (3, 'Jeep'), (4, 'Van&MiniVan'), (5, 'SUV or crossover'), (6, 'Van')]),
        ),
        migrations.AlterField(
            model_name='carpricepredictionmodel',
            name='engine_type',
            field=models.IntegerField(choices=[(1, 'Petrol'), (2, 'Diesel'), (3, 'Hybrid')]),
        ),
        migrations.AlterField(
            model_name='carpricepredictionmodel',
            name='transmission',
            field=models.IntegerField(choices=[(1, 'Auto'), (2, 'Manual')]),
        ),
    ]
